[project]
name = "python"
version = "0.1.0"
description = "Weighted likelihood models for simulated data"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.2.4",
    "pandas>=2.2.3",
    "pymc>=5.22.0",
]
